<?php
///**
// * @var Webinse_Faq_Block_Faq
// */
//?>
<!---->
<!---->
<?php //$helper     = Mage::helper('faq') ?>
<?php //$collection = $this->getAllFaq() ?>
<!---->
<!---->
<!---->
<!--<div class = "container-fluid" style = "margin-bottom: 30px; margin-top: 30px">-->
<!--    <div class = "row text-center">-->
<!--        <h2>--><?php //echo $helper -> __('Frequently Asked Questions'); ?><!--</h2>-->
<!--    </div>-->
<!--</div>-->
<!---->
<!---->
<?php //if ($collection -> getSize()): ?>
<!--    --><?//foreach ($collection as $val):?>
<!--          <div class = "container-fluid">-->
<!--            <div class = "row">-->
<!--                <div class = "panel panel-primary">-->
<!--                    <div class = "panel-heading text-center">-->
<!--                        --><?php //echo $helper -> __('Records number'); ?>
<!--                        &nbsp;-->
<!--                        &nbsp;-->
<!--                        &nbsp;-->
<!--                        <b>--><?//echo $val -> getId();?><!--</b>-->
<!--                    </div>-->
<!--                    <div class = "panel-body">-->
<!--                        <div class = "col-md-8">-->
<!--                            <h4>-->
<!--                                --><?//echo $val -> getQuestion()?>
<!--                                &nbsp;-->
<!--                                <hr>-->
<!--                                &nbsp;-->
<!--                                --><?//echo $val -> getAnswer()?>
<!--                            </h4>-->
<!--                        </div>-->
<!--                        <div class = "col-md-4 text-center">-->
<!--                            --><?// echo $helper -> Link($helper -> __('Delete'),Mage::getUrl('faq/index/deleteFaqById',array('id' => $val -> getId())),array('class'=>'text-danger'))?>
<!--                            <br>-->
<!--                            --><?// echo $helper -> Link($helper -> __('Update'),Mage::getUrl('faq/index/editFaqById',array('id' => $val -> getId())),array('class'=>'text-danger'))?>
<!--                        </div>-->
<!--                    </div>-->
<!--                    <div class = "panel-footer">-->
<!--                        --><?//echo $helper -> __('User with id')."  ".$val -> getId()?>
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!---->
<!--    --><?//endforeach;?>
<!---->
<!---->
<?php //endif; ?>
<!---->
<!---->
<!---->
<!---->
<!---->
<!--<div class="container-fluid">-->
<!--    <div class="row text-center" style="width: 100%; text-decoration: none; font-size: 16px; font-weight: bold">-->
<!---->
<!--        --><?// echo $helper->Link($helper->__('New record'),Mage::getUrl('faq/index/AddNewFaq'),array('class'=>'text-danger'))?>
<!--    </div>-->
<!--</div>-->


<h1>TESt</h1>
